// Code generated from the AWS service reference using cmd/gen; DO NOT EDIT.
//
// Service: sagemaker
// Source: https://servicereference.us-east-1.amazonaws.com/v1/sagemaker/sagemaker.json
// Functions: 73
//
// Regenerate with: make gen

package arnspec

func init() {
	register([]Spec{
		{Name: "sagemaker_action", Service: "sagemaker", Resource: "action", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:action/${ActionName}"},
		{Name: "sagemaker_ai_benchmark_job", Service: "sagemaker", Resource: "ai-benchmark-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:ai-benchmark-job/${AIBenchmarkJobName}"},
		{Name: "sagemaker_ai_recommendation_job", Service: "sagemaker", Resource: "ai-recommendation-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:ai-recommendation-job/${AIRecommendationJobName}"},
		{Name: "sagemaker_ai_workload_config", Service: "sagemaker", Resource: "ai-workload-config", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:ai-workload-config/${AIWorkloadConfigName}"},
		{Name: "sagemaker_algorithm", Service: "sagemaker", Resource: "algorithm", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:algorithm/${AlgorithmName}"},
		{Name: "sagemaker_app", Service: "sagemaker", Resource: "app", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:app/${DomainId}/${UserProfileName}/${AppType}/${AppName}"},
		{Name: "sagemaker_app_image_config", Service: "sagemaker", Resource: "app-image-config", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:app-image-config/${AppImageConfigName}"},
		{Name: "sagemaker_artifact", Service: "sagemaker", Resource: "artifact", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:artifact/${HashOfArtifactSource}"},
		{Name: "sagemaker_automl_job", Service: "sagemaker", Resource: "automl-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:automl-job/${AutoMLJobJobName}"},
		{Name: "sagemaker_cluster", Service: "sagemaker", Resource: "cluster", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:cluster/${ClusterId}"},
		{Name: "sagemaker_cluster_scheduler_config", Service: "sagemaker", Resource: "cluster-scheduler-config", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:cluster-scheduler-config/${ClusterSchedulerConfigId}"},
		{Name: "sagemaker_code_repository", Service: "sagemaker", Resource: "code-repository", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:code-repository/${CodeRepositoryName}"},
		{Name: "sagemaker_compilation_job", Service: "sagemaker", Resource: "compilation-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:compilation-job/${CompilationJobName}"},
		{Name: "sagemaker_compute_quota", Service: "sagemaker", Resource: "compute-quota", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:compute-quota/${ComputeQuotaId}"},
		{Name: "sagemaker_context", Service: "sagemaker", Resource: "context", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:context/${ContextName}"},
		{Name: "sagemaker_data_quality_job_definition", Service: "sagemaker", Resource: "data-quality-job-definition", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:data-quality-job-definition/${DataQualityJobDefinitionName}"},
		{Name: "sagemaker_device", Service: "sagemaker", Resource: "device", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:device-fleet/${DeviceFleetName}/device/${DeviceName}"},
		{Name: "sagemaker_device_fleet", Service: "sagemaker", Resource: "device-fleet", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:device-fleet/${DeviceFleetName}"},
		{Name: "sagemaker_domain", Service: "sagemaker", Resource: "domain", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:domain/${DomainId}"},
		{Name: "sagemaker_edge_deployment_plan", Service: "sagemaker", Resource: "edge-deployment-plan", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:edge-deployment/${EdgeDeploymentPlanName}"},
		{Name: "sagemaker_edge_packaging_job", Service: "sagemaker", Resource: "edge-packaging-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:edge-packaging-job/${EdgePackagingJobName}"},
		{Name: "sagemaker_endpoint", Service: "sagemaker", Resource: "endpoint", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:endpoint/${EndpointName}"},
		{Name: "sagemaker_endpoint_config", Service: "sagemaker", Resource: "endpoint-config", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:endpoint-config/${EndpointConfigName}"},
		{Name: "sagemaker_experiment", Service: "sagemaker", Resource: "experiment", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:experiment/${ExperimentName}"},
		{Name: "sagemaker_experiment_trial", Service: "sagemaker", Resource: "experiment-trial", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:experiment-trial/${TrialName}"},
		{Name: "sagemaker_experiment_trial_component", Service: "sagemaker", Resource: "experiment-trial-component", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:experiment-trial-component/${TrialComponentName}"},
		{Name: "sagemaker_feature_group", Service: "sagemaker", Resource: "feature-group", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:feature-group/${FeatureGroupName}"},
		{Name: "sagemaker_flow_definition", Service: "sagemaker", Resource: "flow-definition", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:flow-definition/${FlowDefinitionName}"},
		{Name: "sagemaker_hub", Service: "sagemaker", Resource: "hub", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:hub/${HubName}"},
		{Name: "sagemaker_hub_content", Service: "sagemaker", Resource: "hub-content", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:hub-content/${HubName}/${HubContentType}/${HubContentName}"},
		{Name: "sagemaker_human_loop", Service: "sagemaker", Resource: "human-loop", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:human-loop/${HumanLoopName}"},
		{Name: "sagemaker_human_task_ui", Service: "sagemaker", Resource: "human-task-ui", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:human-task-ui/${HumanTaskUiName}"},
		{Name: "sagemaker_hyper_parameter_tuning_job", Service: "sagemaker", Resource: "hyper-parameter-tuning-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:hyper-parameter-tuning-job/${HyperParameterTuningJobName}"},
		{Name: "sagemaker_image", Service: "sagemaker", Resource: "image", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:image/${ImageName}"},
		{Name: "sagemaker_image_version", Service: "sagemaker", Resource: "image-version", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:image-version/${ImageName}/${Version}"},
		{Name: "sagemaker_inference_component", Service: "sagemaker", Resource: "inference-component", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:inference-component/${InferenceComponentName}"},
		{Name: "sagemaker_inference_experiment", Service: "sagemaker", Resource: "inference-experiment", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:inference-experiment/${InferenceExperimentName}"},
		{Name: "sagemaker_inference_recommendations_job", Service: "sagemaker", Resource: "inference-recommendations-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:inference-recommendations-job/${InferenceRecommendationsJobName}"},
		{Name: "sagemaker_job", Service: "sagemaker", Resource: "job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:job/${JobCategory}/${JobName}"},
		{Name: "sagemaker_labeling_job", Service: "sagemaker", Resource: "labeling-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:labeling-job/${LabelingJobName}"},
		{Name: "sagemaker_lineage_group", Service: "sagemaker", Resource: "lineage-group", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:lineage-group/${LineageGroupName}"},
		{Name: "sagemaker_mlflow_app", Service: "sagemaker", Resource: "mlflow-app", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:mlflow-app/${MLflowAppId}"},
		{Name: "sagemaker_mlflow_tracking_server", Service: "sagemaker", Resource: "mlflow-tracking-server", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:mlflow-tracking-server/${MlflowTrackingServerName}"},
		{Name: "sagemaker_model", Service: "sagemaker", Resource: "model", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model/${ModelName}"},
		{Name: "sagemaker_model_bias_job_definition", Service: "sagemaker", Resource: "model-bias-job-definition", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-bias-job-definition/${ModelBiasJobDefinitionName}"},
		{Name: "sagemaker_model_card", Service: "sagemaker", Resource: "model-card", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-card/${ModelCardName}"},
		{Name: "sagemaker_model_card_export_job", Service: "sagemaker", Resource: "model-card-export-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-card/${ModelCardName}/export-job/${ExportJobName}"},
		{Name: "sagemaker_model_explainability_job_definition", Service: "sagemaker", Resource: "model-explainability-job-definition", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-explainability-job-definition/${ModelExplainabilityJobDefinitionName}"},
		{Name: "sagemaker_model_package", Service: "sagemaker", Resource: "model-package", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-package/${ModelPackageName}"},
		{Name: "sagemaker_model_package_group", Service: "sagemaker", Resource: "model-package-group", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-package-group/${ModelPackageGroupName}"},
		{Name: "sagemaker_model_quality_job_definition", Service: "sagemaker", Resource: "model-quality-job-definition", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:model-quality-job-definition/${ModelQualityJobDefinitionName}"},
		{Name: "sagemaker_monitoring_schedule", Service: "sagemaker", Resource: "monitoring-schedule", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:monitoring-schedule/${MonitoringScheduleName}"},
		{Name: "sagemaker_monitoring_schedule_alert", Service: "sagemaker", Resource: "monitoring-schedule-alert", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:monitoring-schedule/${MonitoringScheduleName}/alert/${MonitoringScheduleAlertName}"},
		{Name: "sagemaker_notebook_instance", Service: "sagemaker", Resource: "notebook-instance", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:notebook-instance/${NotebookInstanceName}"},
		{Name: "sagemaker_notebook_instance_lifecycle_config", Service: "sagemaker", Resource: "notebook-instance-lifecycle-config", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:notebook-instance-lifecycle-config/${NotebookInstanceLifecycleConfigName}"},
		{Name: "sagemaker_optimization_job", Service: "sagemaker", Resource: "optimization-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:optimization-job/${OptimizationJobName}"},
		{Name: "sagemaker_partner_app", Service: "sagemaker", Resource: "partner-app", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:partner-app/${AppId}"},
		{Name: "sagemaker_pipeline", Service: "sagemaker", Resource: "pipeline", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:pipeline/${PipelineName}"},
		{Name: "sagemaker_pipeline_execution", Service: "sagemaker", Resource: "pipeline-execution", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:pipeline/${PipelineName}/execution/${RandomString}"},
		{Name: "sagemaker_processing_job", Service: "sagemaker", Resource: "processing-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:processing-job/${ProcessingJobName}"},
		{Name: "sagemaker_project", Service: "sagemaker", Resource: "project", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:project/${ProjectName}"},
		{Name: "sagemaker_reserved_capacity", Service: "sagemaker", Resource: "reserved-capacity", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:reserved-capacity/${RandomString}"},
		{Name: "sagemaker_sagemaker_catalog", Service: "sagemaker", Resource: "sagemaker-catalog", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:sagemaker-catalog/${ResourceCatalogName}"},
		{Name: "sagemaker_shared_model", Service: "sagemaker", Resource: "shared-model", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:shared-model/${SharedModelId}"},
		{Name: "sagemaker_shared_model_event", Service: "sagemaker", Resource: "shared-model-event", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:shared-model-event/${EventId}"},
		{Name: "sagemaker_space", Service: "sagemaker", Resource: "space", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:space/${DomainId}/${SpaceName}"},
		{Name: "sagemaker_studio_lifecycle_config", Service: "sagemaker", Resource: "studio-lifecycle-config", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:studio-lifecycle-config/${StudioLifecycleConfigName}"},
		{Name: "sagemaker_training_job", Service: "sagemaker", Resource: "training-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:training-job/${TrainingJobName}"},
		{Name: "sagemaker_training_plan", Service: "sagemaker", Resource: "training-plan", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:training-plan/${TrainingPlanName}"},
		{Name: "sagemaker_transform_job", Service: "sagemaker", Resource: "transform-job", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:transform-job/${TransformJobName}"},
		{Name: "sagemaker_user_profile", Service: "sagemaker", Resource: "user-profile", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:user-profile/${DomainId}/${UserProfileName}"},
		{Name: "sagemaker_workforce", Service: "sagemaker", Resource: "workforce", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:workforce/${WorkforceName}"},
		{Name: "sagemaker_workteam", Service: "sagemaker", Resource: "workteam", Template: "arn:${Partition}:sagemaker:${Region}:${Account}:workteam/${WorkteamName}"},
	})
}
