// Code generated from the AWS service reference using cmd/gen; DO NOT EDIT.
//
// Service: apigateway
// Source: https://servicereference.us-east-1.amazonaws.com/v1/apigateway/apigateway.json
// Functions: 79
//
// Regenerate with: make gen

package arnspec

func init() {
	register([]Spec{
		{Name: "apigateway_access_log_settings", Service: "apigateway", Resource: "AccessLogSettings", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/stages/${StageName}/accesslogsettings"},
		{Name: "apigateway_account", Service: "apigateway", Resource: "Account", Template: "arn:${Partition}:apigateway:${Region}::/account"},
		{Name: "apigateway_api", Service: "apigateway", Resource: "Api", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}"},
		{Name: "apigateway_api_key", Service: "apigateway", Resource: "ApiKey", Template: "arn:${Partition}:apigateway:${Region}::/apikeys/${ApiKeyId}"},
		{Name: "apigateway_api_keys", Service: "apigateway", Resource: "ApiKeys", Template: "arn:${Partition}:apigateway:${Region}::/apikeys"},
		{Name: "apigateway_api_mapping", Service: "apigateway", Resource: "ApiMapping", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}/apimappings/${ApiMappingId}"},
		{Name: "apigateway_api_mappings", Service: "apigateway", Resource: "ApiMappings", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}/apimappings"},
		{Name: "apigateway_apis", Service: "apigateway", Resource: "Apis", Template: "arn:${Partition}:apigateway:${Region}::/apis"},
		{Name: "apigateway_authorizer", Service: "apigateway", Resource: "Authorizer", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/authorizers/${AuthorizerId}"},
		{Name: "apigateway_authorizer_2", Service: "apigateway", Resource: "Authorizer", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/authorizers/${AuthorizerId}"},
		{Name: "apigateway_authorizers", Service: "apigateway", Resource: "Authorizers", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/authorizers"},
		{Name: "apigateway_authorizers_2", Service: "apigateway", Resource: "Authorizers", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/authorizers"},
		{Name: "apigateway_authorizers_cache", Service: "apigateway", Resource: "AuthorizersCache", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/stages/${StageName}/cache/authorizers"},
		{Name: "apigateway_base_path_mapping", Service: "apigateway", Resource: "BasePathMapping", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}/basepathmappings/${BasePath}"},
		{Name: "apigateway_base_path_mappings", Service: "apigateway", Resource: "BasePathMappings", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}/basepathmappings"},
		{Name: "apigateway_client_certificate", Service: "apigateway", Resource: "ClientCertificate", Template: "arn:${Partition}:apigateway:${Region}::/clientcertificates/${ClientCertificateId}"},
		{Name: "apigateway_client_certificates", Service: "apigateway", Resource: "ClientCertificates", Template: "arn:${Partition}:apigateway:${Region}::/clientcertificates"},
		{Name: "apigateway_cors", Service: "apigateway", Resource: "Cors", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/cors"},
		{Name: "apigateway_deployment", Service: "apigateway", Resource: "Deployment", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/deployments/${DeploymentId}"},
		{Name: "apigateway_deployment_2", Service: "apigateway", Resource: "Deployment", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/deployments/${DeploymentId}"},
		{Name: "apigateway_deployments", Service: "apigateway", Resource: "Deployments", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/deployments"},
		{Name: "apigateway_deployments_2", Service: "apigateway", Resource: "Deployments", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/deployments"},
		{Name: "apigateway_documentation_part", Service: "apigateway", Resource: "DocumentationPart", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/documentation/parts/${DocumentationPartId}"},
		{Name: "apigateway_documentation_parts", Service: "apigateway", Resource: "DocumentationParts", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/documentation/parts"},
		{Name: "apigateway_documentation_version", Service: "apigateway", Resource: "DocumentationVersion", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/documentation/versions/${DocumentationVersionId}"},
		{Name: "apigateway_documentation_versions", Service: "apigateway", Resource: "DocumentationVersions", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/documentation/versions"},
		{Name: "apigateway_domain_name", Service: "apigateway", Resource: "DomainName", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}"},
		{Name: "apigateway_domain_name_access_association", Service: "apigateway", Resource: "DomainNameAccessAssociation", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/domainnameaccessassociations/domainname/${DomainName}/${SourceType}/${SourceId}"},
		{Name: "apigateway_domain_name_access_associations", Service: "apigateway", Resource: "DomainNameAccessAssociations", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/domainnameaccessassociations"},
		{Name: "apigateway_domain_names", Service: "apigateway", Resource: "DomainNames", Template: "arn:${Partition}:apigateway:${Region}::/domainnames"},
		{Name: "apigateway_exported_api", Service: "apigateway", Resource: "ExportedAPI", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/exports/${Specification}"},
		{Name: "apigateway_gateway_response", Service: "apigateway", Resource: "GatewayResponse", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/gatewayresponses/${ResponseType}"},
		{Name: "apigateway_gateway_responses", Service: "apigateway", Resource: "GatewayResponses", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/gatewayresponses"},
		{Name: "apigateway_integration", Service: "apigateway", Resource: "Integration", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/integrations/${IntegrationId}"},
		{Name: "apigateway_integration_2", Service: "apigateway", Resource: "Integration", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/resources/${ResourceId}/methods/${HttpMethodType}/integration"},
		{Name: "apigateway_integration_response", Service: "apigateway", Resource: "IntegrationResponse", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/integrations/${IntegrationId}/integrationresponses/${IntegrationResponseId}"},
		{Name: "apigateway_integration_response_2", Service: "apigateway", Resource: "IntegrationResponse", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/resources/${ResourceId}/methods/${HttpMethodType}/integration/responses/${StatusCode}"},
		{Name: "apigateway_integration_responses", Service: "apigateway", Resource: "IntegrationResponses", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/integrations/${IntegrationId}/integrationresponses"},
		{Name: "apigateway_integrations", Service: "apigateway", Resource: "Integrations", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/integrations"},
		{Name: "apigateway_method", Service: "apigateway", Resource: "Method", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/resources/${ResourceId}/methods/${HttpMethodType}"},
		{Name: "apigateway_method_response", Service: "apigateway", Resource: "MethodResponse", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/resources/${ResourceId}/methods/${HttpMethodType}/responses/${StatusCode}"},
		{Name: "apigateway_model", Service: "apigateway", Resource: "Model", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/models/${ModelId}"},
		{Name: "apigateway_model_2", Service: "apigateway", Resource: "Model", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/models/${ModelName}"},
		{Name: "apigateway_model_template", Service: "apigateway", Resource: "ModelTemplate", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/models/${ModelId}/template"},
		{Name: "apigateway_models", Service: "apigateway", Resource: "Models", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/models"},
		{Name: "apigateway_models_2", Service: "apigateway", Resource: "Models", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/models"},
		{Name: "apigateway_portal", Service: "apigateway", Resource: "Portal", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/portals/${PortalId}"},
		{Name: "apigateway_portal_product", Service: "apigateway", Resource: "PortalProduct", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/portalproducts/${PortalProductId}"},
		{Name: "apigateway_private_base_path_mapping", Service: "apigateway", Resource: "PrivateBasePathMapping", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}+${DomainIdentifier}/basepathmappings/${BasePath}"},
		{Name: "apigateway_private_base_path_mappings", Service: "apigateway", Resource: "PrivateBasePathMappings", Template: "arn:${Partition}:apigateway:${Region}::/domainnames/${DomainName}+${DomainIdentifier}/basepathmappings"},
		{Name: "apigateway_private_domain_name", Service: "apigateway", Resource: "PrivateDomainName", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/domainnames/${DomainName}+${DomainIdentifier}"},
		{Name: "apigateway_product_page", Service: "apigateway", Resource: "ProductPage", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/portalproducts/${PortalProductId}/productpages/${ProductPageId}"},
		{Name: "apigateway_product_rest_endpoint_page", Service: "apigateway", Resource: "ProductRestEndpointPage", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/portalproducts/${PortalProductId}/productrestendpointpages/${ProductRestEndpointPageId}"},
		{Name: "apigateway_request_validator", Service: "apigateway", Resource: "RequestValidator", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/requestvalidators/${RequestValidatorId}"},
		{Name: "apigateway_request_validators", Service: "apigateway", Resource: "RequestValidators", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/requestvalidators"},
		{Name: "apigateway_resource", Service: "apigateway", Resource: "Resource", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/resources/${ResourceId}"},
		{Name: "apigateway_resources", Service: "apigateway", Resource: "Resources", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/resources"},
		{Name: "apigateway_rest_api", Service: "apigateway", Resource: "RestApi", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}"},
		{Name: "apigateway_rest_apis", Service: "apigateway", Resource: "RestApis", Template: "arn:${Partition}:apigateway:${Region}::/restapis"},
		{Name: "apigateway_route", Service: "apigateway", Resource: "Route", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/routes/${RouteId}"},
		{Name: "apigateway_route_request_parameter", Service: "apigateway", Resource: "RouteRequestParameter", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/routes/${RouteId}/requestparameters/${RequestParameterKey}"},
		{Name: "apigateway_route_response", Service: "apigateway", Resource: "RouteResponse", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/routes/${RouteId}/routeresponses/${RouteResponseId}"},
		{Name: "apigateway_route_responses", Service: "apigateway", Resource: "RouteResponses", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/routes/${RouteId}/routeresponses"},
		{Name: "apigateway_route_settings", Service: "apigateway", Resource: "RouteSettings", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/stages/${StageName}/routesettings/${RouteKey}"},
		{Name: "apigateway_routes", Service: "apigateway", Resource: "Routes", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/routes"},
		{Name: "apigateway_routing_rule", Service: "apigateway", Resource: "RoutingRule", Template: "arn:${Partition}:apigateway:${Region}:${Account}:/domainnames/${DomainName}/routingrules/${RoutingRuleId}"},
		{Name: "apigateway_sdk", Service: "apigateway", Resource: "Sdk", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/stages/${StageName}/sdks/${SdkType}"},
		{Name: "apigateway_stage", Service: "apigateway", Resource: "Stage", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/stages/${StageName}"},
		{Name: "apigateway_stage_2", Service: "apigateway", Resource: "Stage", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/stages/${StageName}"},
		{Name: "apigateway_stages", Service: "apigateway", Resource: "Stages", Template: "arn:${Partition}:apigateway:${Region}::/apis/${ApiId}/stages"},
		{Name: "apigateway_stages_2", Service: "apigateway", Resource: "Stages", Template: "arn:${Partition}:apigateway:${Region}::/restapis/${RestApiId}/stages"},
		{Name: "apigateway_tags", Service: "apigateway", Resource: "Tags", Template: "arn:${Partition}:apigateway:${Region}::/tags/${UrlEncodedResourceARN}"},
		{Name: "apigateway_template", Service: "apigateway", Resource: "Template", Template: "arn:${Partition}:apigateway:${Region}::/restapis/models/${ModelName}/template"},
		{Name: "apigateway_usage_plan", Service: "apigateway", Resource: "UsagePlan", Template: "arn:${Partition}:apigateway:${Region}::/usageplans/${UsagePlanId}"},
		{Name: "apigateway_usage_plan_key", Service: "apigateway", Resource: "UsagePlanKey", Template: "arn:${Partition}:apigateway:${Region}::/usageplans/${UsagePlanId}/keys/${Id}"},
		{Name: "apigateway_usage_plan_keys", Service: "apigateway", Resource: "UsagePlanKeys", Template: "arn:${Partition}:apigateway:${Region}::/usageplans/${UsagePlanId}/keys"},
		{Name: "apigateway_usage_plans", Service: "apigateway", Resource: "UsagePlans", Template: "arn:${Partition}:apigateway:${Region}::/usageplans"},
		{Name: "apigateway_vpc_link", Service: "apigateway", Resource: "VpcLink", Template: "arn:${Partition}:apigateway:${Region}::/vpclinks/${VpcLinkId}"},
		{Name: "apigateway_vpc_links", Service: "apigateway", Resource: "VpcLinks", Template: "arn:${Partition}:apigateway:${Region}::/vpclinks"},
	})
}
