// Code generated from the AWS service reference using cmd/gen; DO NOT EDIT.
//
// Service: ec2
// Source: https://servicereference.us-east-1.amazonaws.com/v1/ec2/ec2.json
// Functions: 114
//
// Regenerate with: make gen

package arnspec

func init() {
	register([]Spec{
		{Name: "ec2_application_status_check", Service: "ec2", Resource: "application-status-check", Template: "arn:${Partition}:ec2:${Region}:${Account}:application-status-check/${ApplicationStatusCheckId}"},
		{Name: "ec2_capacity_block", Service: "ec2", Resource: "capacity-block", Template: "arn:${Partition}:ec2:${Region}:${Account}:capacity-block/${CapacityBlockId}"},
		{Name: "ec2_capacity_manager_data_export", Service: "ec2", Resource: "capacity-manager-data-export", Template: "arn:${Partition}:ec2:${Region}:${Account}:capacity-manager-data-export/${CapacityManagerDataExportId}"},
		{Name: "ec2_capacity_reservation", Service: "ec2", Resource: "capacity-reservation", Template: "arn:${Partition}:ec2:${Region}:${Account}:capacity-reservation/${CapacityReservationId}"},
		{Name: "ec2_capacity_reservation_cancellation_quote", Service: "ec2", Resource: "capacity-reservation-cancellation-quote", Template: "arn:${Partition}:ec2:${Region}:${Account}:capacity-reservation-cancellation-quote/${CapacityReservationCancellationQuoteId}"},
		{Name: "ec2_capacity_reservation_fleet", Service: "ec2", Resource: "capacity-reservation-fleet", Template: "arn:${Partition}:ec2:${Region}:${Account}:capacity-reservation-fleet/${CapacityReservationFleetId}"},
		{Name: "ec2_carrier_gateway", Service: "ec2", Resource: "carrier-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:carrier-gateway/${CarrierGatewayId}"},
		{Name: "ec2_certificate", Service: "ec2", Resource: "certificate", Template: "arn:${Partition}:acm:${Region}:${Account}:certificate/${CertificateId}"},
		{Name: "ec2_client_vpn_endpoint", Service: "ec2", Resource: "client-vpn-endpoint", Template: "arn:${Partition}:ec2:${Region}:${Account}:client-vpn-endpoint/${ClientVpnEndpointId}"},
		{Name: "ec2_coip_pool", Service: "ec2", Resource: "coip-pool", Template: "arn:${Partition}:ec2:${Region}:${Account}:coip-pool/${Ipv4PoolCoipId}"},
		{Name: "ec2_customer_gateway", Service: "ec2", Resource: "customer-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:customer-gateway/${CustomerGatewayId}"},
		{Name: "ec2_declarative_policies_report", Service: "ec2", Resource: "declarative-policies-report", Template: "arn:${Partition}:ec2:${Region}:${Account}:declarative-policies-report/${DeclarativePoliciesReportId}"},
		{Name: "ec2_dedicated_host", Service: "ec2", Resource: "dedicated-host", Template: "arn:${Partition}:ec2:${Region}:${Account}:dedicated-host/${DedicatedHostId}"},
		{Name: "ec2_dhcp_options", Service: "ec2", Resource: "dhcp-options", Template: "arn:${Partition}:ec2:${Region}:${Account}:dhcp-options/${DhcpOptionsId}"},
		{Name: "ec2_egress_only_internet_gateway", Service: "ec2", Resource: "egress-only-internet-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:egress-only-internet-gateway/${EgressOnlyInternetGatewayId}"},
		{Name: "ec2_elastic_gpu", Service: "ec2", Resource: "elastic-gpu", Template: "arn:${Partition}:ec2:${Region}:${Account}:elastic-gpu/${ElasticGpuId}"},
		{Name: "ec2_elastic_inference", Service: "ec2", Resource: "elastic-inference", Template: "arn:${Partition}:elastic-inference:${Region}:${Account}:elastic-inference-accelerator/${AcceleratorId}"},
		{Name: "ec2_elastic_ip", Service: "ec2", Resource: "elastic-ip", Template: "arn:${Partition}:ec2:${Region}:${Account}:elastic-ip/${AllocationId}"},
		{Name: "ec2_export_image_task", Service: "ec2", Resource: "export-image-task", Template: "arn:${Partition}:ec2:${Region}:${Account}:export-image-task/${ExportImageTaskId}"},
		{Name: "ec2_export_instance_task", Service: "ec2", Resource: "export-instance-task", Template: "arn:${Partition}:ec2:${Region}:${Account}:export-instance-task/${ExportTaskId}"},
		{Name: "ec2_fleet", Service: "ec2", Resource: "fleet", Template: "arn:${Partition}:ec2:${Region}:${Account}:fleet/${FleetId}"},
		{Name: "ec2_fpga_image", Service: "ec2", Resource: "fpga-image", Template: "arn:${Partition}:ec2:${Region}:${Account}:fpga-image/${FpgaImageId}"},
		{Name: "ec2_group", Service: "ec2", Resource: "group", Template: "arn:${Partition}:resource-groups:${Region}:${Account}:group/${GroupName}"},
		{Name: "ec2_host_reservation", Service: "ec2", Resource: "host-reservation", Template: "arn:${Partition}:ec2:${Region}:${Account}:host-reservation/${HostReservationId}"},
		{Name: "ec2_image", Service: "ec2", Resource: "image", Template: "arn:${Partition}:ec2:${Region}::image/${ImageId}"},
		{Name: "ec2_image_usage_report", Service: "ec2", Resource: "image-usage-report", Template: "arn:${Partition}:ec2:${Region}:${Account}:image-usage-report/${ImageUsageReportId}"},
		{Name: "ec2_import_image_task", Service: "ec2", Resource: "import-image-task", Template: "arn:${Partition}:ec2:${Region}:${Account}:import-image-task/${ImportImageTaskId}"},
		{Name: "ec2_import_snapshot_task", Service: "ec2", Resource: "import-snapshot-task", Template: "arn:${Partition}:ec2:${Region}:${Account}:import-snapshot-task/${ImportSnapshotTaskId}"},
		{Name: "ec2_instance", Service: "ec2", Resource: "instance", Template: "arn:${Partition}:ec2:${Region}:${Account}:instance/${InstanceId}"},
		{Name: "ec2_instance_connect_endpoint", Service: "ec2", Resource: "instance-connect-endpoint", Template: "arn:${Partition}:ec2:${Region}:${Account}:instance-connect-endpoint/${InstanceConnectEndpointId}"},
		{Name: "ec2_instance_event_window", Service: "ec2", Resource: "instance-event-window", Template: "arn:${Partition}:ec2:${Region}:${Account}:instance-event-window/${InstanceEventWindowId}"},
		{Name: "ec2_internet_gateway", Service: "ec2", Resource: "internet-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:internet-gateway/${InternetGatewayId}"},
		{Name: "ec2_ipam", Service: "ec2", Resource: "ipam", Template: "arn:${Partition}:ec2::${Account}:ipam/${IpamId}"},
		{Name: "ec2_ipam_external_resource_verification_token", Service: "ec2", Resource: "ipam-external-resource-verification-token", Template: "arn:${Partition}:ec2::${Account}:ipam-external-resource-verification-token/${IpamExternalResourceVerificationTokenId}"},
		{Name: "ec2_ipam_internet_registry_association", Service: "ec2", Resource: "ipam-internet-registry-association", Template: "arn:${Partition}:ec2::${Account}:ipam-internet-registry-association/${IpamInternetRegistryAssociationId}"},
		{Name: "ec2_ipam_policy", Service: "ec2", Resource: "ipam-policy", Template: "arn:${Partition}:ec2::${Account}:ipam-policy/${IpamPolicyId}"},
		{Name: "ec2_ipam_pool", Service: "ec2", Resource: "ipam-pool", Template: "arn:${Partition}:ec2::${Account}:ipam-pool/${IpamPoolId}"},
		{Name: "ec2_ipam_pool_allocation", Service: "ec2", Resource: "ipam-pool-allocation", Template: "arn:${Partition}:ec2:${Region}:${Account}:ipam-pool-allocation/${IpamPoolAllocationId}"},
		{Name: "ec2_ipam_prefix_list_resolver", Service: "ec2", Resource: "ipam-prefix-list-resolver", Template: "arn:${Partition}:ec2::${Account}:ipam-prefix-list-resolver/${IpamPrefixListResolverId}"},
		{Name: "ec2_ipam_prefix_list_resolver_target", Service: "ec2", Resource: "ipam-prefix-list-resolver-target", Template: "arn:${Partition}:ec2::${Account}:ipam-prefix-list-resolver-target/${IpamPrefixListResolverTargetId}"},
		{Name: "ec2_ipam_resource_discovery", Service: "ec2", Resource: "ipam-resource-discovery", Template: "arn:${Partition}:ec2::${Account}:ipam-resource-discovery/${IpamResourceDiscoveryId}"},
		{Name: "ec2_ipam_resource_discovery_association", Service: "ec2", Resource: "ipam-resource-discovery-association", Template: "arn:${Partition}:ec2::${Account}:ipam-resource-discovery-association/${IpamResourceDiscoveryAssociationId}"},
		{Name: "ec2_ipam_scope", Service: "ec2", Resource: "ipam-scope", Template: "arn:${Partition}:ec2::${Account}:ipam-scope/${IpamScopeId}"},
		{Name: "ec2_ipv4pool_ec2", Service: "ec2", Resource: "ipv4pool-ec2", Template: "arn:${Partition}:ec2:${Region}:${Account}:ipv4pool-ec2/${Ipv4PoolEc2Id}"},
		{Name: "ec2_ipv6pool_ec2", Service: "ec2", Resource: "ipv6pool-ec2", Template: "arn:${Partition}:ec2:${Region}:${Account}:ipv6pool-ec2/${Ipv6PoolEc2Id}"},
		{Name: "ec2_key_pair", Service: "ec2", Resource: "key-pair", Template: "arn:${Partition}:ec2:${Region}:${Account}:key-pair/${KeyPairName}"},
		{Name: "ec2_launch_template", Service: "ec2", Resource: "launch-template", Template: "arn:${Partition}:ec2:${Region}:${Account}:launch-template/${LaunchTemplateId}"},
		{Name: "ec2_license_configuration", Service: "ec2", Resource: "license-configuration", Template: "arn:${Partition}:license-manager:${Region}:${Account}:license-configuration:${LicenseConfigurationId}"},
		{Name: "ec2_local_gateway", Service: "ec2", Resource: "local-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:local-gateway/${LocalGatewayId}"},
		{Name: "ec2_local_gateway_route_table", Service: "ec2", Resource: "local-gateway-route-table", Template: "arn:${Partition}:ec2:${Region}:${Account}:local-gateway-route-table/${LocalGatewayRoutetableId}"},
		{Name: "ec2_local_gateway_route_table_virtual_interface_group_association", Service: "ec2", Resource: "local-gateway-route-table-virtual-interface-group-association", Template: "arn:${Partition}:ec2:${Region}:${Account}:local-gateway-route-table-virtual-interface-group-association/${LocalGatewayRouteTableVirtualInterfaceGroupAssociationId}"},
		{Name: "ec2_local_gateway_route_table_vpc_association", Service: "ec2", Resource: "local-gateway-route-table-vpc-association", Template: "arn:${Partition}:ec2:${Region}:${Account}:local-gateway-route-table-vpc-association/${LocalGatewayRouteTableVpcAssociationId}"},
		{Name: "ec2_local_gateway_virtual_interface", Service: "ec2", Resource: "local-gateway-virtual-interface", Template: "arn:${Partition}:ec2:${Region}:${Account}:local-gateway-virtual-interface/${LocalGatewayVirtualInterfaceId}"},
		{Name: "ec2_local_gateway_virtual_interface_group", Service: "ec2", Resource: "local-gateway-virtual-interface-group", Template: "arn:${Partition}:ec2:${Region}:${Account}:local-gateway-virtual-interface-group/${LocalGatewayVirtualInterfaceGroupId}"},
		{Name: "ec2_mac_modification_task", Service: "ec2", Resource: "mac-modification-task", Template: "arn:${Partition}:ec2:${Region}:${Account}:mac-modification-task/${MacModificationTaskId}"},
		{Name: "ec2_natgateway", Service: "ec2", Resource: "natgateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:natgateway/${NatGatewayId}"},
		{Name: "ec2_network_acl", Service: "ec2", Resource: "network-acl", Template: "arn:${Partition}:ec2:${Region}:${Account}:network-acl/${NaclId}"},
		{Name: "ec2_network_insights_access_scope", Service: "ec2", Resource: "network-insights-access-scope", Template: "arn:${Partition}:ec2:${Region}:${Account}:network-insights-access-scope/${NetworkInsightsAccessScopeId}"},
		{Name: "ec2_network_insights_access_scope_analysis", Service: "ec2", Resource: "network-insights-access-scope-analysis", Template: "arn:${Partition}:ec2:${Region}:${Account}:network-insights-access-scope-analysis/${NetworkInsightsAccessScopeAnalysisId}"},
		{Name: "ec2_network_insights_analysis", Service: "ec2", Resource: "network-insights-analysis", Template: "arn:${Partition}:ec2:${Region}:${Account}:network-insights-analysis/${NetworkInsightsAnalysisId}"},
		{Name: "ec2_network_insights_path", Service: "ec2", Resource: "network-insights-path", Template: "arn:${Partition}:ec2:${Region}:${Account}:network-insights-path/${NetworkInsightsPathId}"},
		{Name: "ec2_network_interface", Service: "ec2", Resource: "network-interface", Template: "arn:${Partition}:ec2:${Region}:${Account}:network-interface/${NetworkInterfaceId}"},
		{Name: "ec2_outpost_lag", Service: "ec2", Resource: "outpost-lag", Template: "arn:${Partition}:ec2:${Region}:${Account}:outpost-lag/${OutpostLagId}"},
		{Name: "ec2_placement_group", Service: "ec2", Resource: "placement-group", Template: "arn:${Partition}:ec2:${Region}:${Account}:placement-group/${PlacementGroupName}"},
		{Name: "ec2_prefix_list", Service: "ec2", Resource: "prefix-list", Template: "arn:${Partition}:ec2:${Region}:${Account}:prefix-list/${PrefixListId}"},
		{Name: "ec2_replace_root_volume_task", Service: "ec2", Resource: "replace-root-volume-task", Template: "arn:${Partition}:ec2:${Region}:${Account}:replace-root-volume-task/${ReplaceRootVolumeTaskId}"},
		{Name: "ec2_reserved_instances", Service: "ec2", Resource: "reserved-instances", Template: "arn:${Partition}:ec2:${Region}:${Account}:reserved-instances/${ReservationId}"},
		{Name: "ec2_role", Service: "ec2", Resource: "role", Template: "arn:${Partition}:iam::${Account}:role/${RoleNameWithPath}"},
		{Name: "ec2_route_server", Service: "ec2", Resource: "route-server", Template: "arn:${Partition}:ec2:${Region}:${Account}:route-server/${RouteServerId}"},
		{Name: "ec2_route_server_endpoint", Service: "ec2", Resource: "route-server-endpoint", Template: "arn:${Partition}:ec2:${Region}:${Account}:route-server-endpoint/${RouteServerEndpointId}"},
		{Name: "ec2_route_server_peer", Service: "ec2", Resource: "route-server-peer", Template: "arn:${Partition}:ec2:${Region}:${Account}:route-server-peer/${RouteServerPeerId}"},
		{Name: "ec2_route_table", Service: "ec2", Resource: "route-table", Template: "arn:${Partition}:ec2:${Region}:${Account}:route-table/${RouteTableId}"},
		{Name: "ec2_secondary_interface", Service: "ec2", Resource: "secondary-interface", Template: "arn:${Partition}:ec2:${Region}:${Account}:secondary-interface/${SecondaryInterfaceId}"},
		{Name: "ec2_secondary_network", Service: "ec2", Resource: "secondary-network", Template: "arn:${Partition}:ec2:${Region}:${Account}:secondary-network/${SecondaryNetworkId}"},
		{Name: "ec2_secondary_subnet", Service: "ec2", Resource: "secondary-subnet", Template: "arn:${Partition}:ec2:${Region}:${Account}:secondary-subnet/${SecondarySubnetId}"},
		{Name: "ec2_security_group", Service: "ec2", Resource: "security-group", Template: "arn:${Partition}:ec2:${Region}:${Account}:security-group/${SecurityGroupId}"},
		{Name: "ec2_security_group_rule", Service: "ec2", Resource: "security-group-rule", Template: "arn:${Partition}:ec2:${Region}:${Account}:security-group-rule/${SecurityGroupRuleId}"},
		{Name: "ec2_snapshot", Service: "ec2", Resource: "snapshot", Template: "arn:${Partition}:ec2:${Region}::snapshot/${SnapshotId}"},
		{Name: "ec2_spot_fleet_request", Service: "ec2", Resource: "spot-fleet-request", Template: "arn:${Partition}:ec2:${Region}:${Account}:spot-fleet-request/${SpotFleetRequestId}"},
		{Name: "ec2_spot_instances_request", Service: "ec2", Resource: "spot-instances-request", Template: "arn:${Partition}:ec2:${Region}:${Account}:spot-instances-request/${SpotInstanceRequestId}"},
		{Name: "ec2_subnet", Service: "ec2", Resource: "subnet", Template: "arn:${Partition}:ec2:${Region}:${Account}:subnet/${SubnetId}"},
		{Name: "ec2_subnet_cidr_reservation", Service: "ec2", Resource: "subnet-cidr-reservation", Template: "arn:${Partition}:ec2:${Region}:${Account}:subnet-cidr-reservation/${SubnetCidrReservationId}"},
		{Name: "ec2_traffic_mirror_filter", Service: "ec2", Resource: "traffic-mirror-filter", Template: "arn:${Partition}:ec2:${Region}:${Account}:traffic-mirror-filter/${TrafficMirrorFilterId}"},
		{Name: "ec2_traffic_mirror_filter_rule", Service: "ec2", Resource: "traffic-mirror-filter-rule", Template: "arn:${Partition}:ec2:${Region}:${Account}:traffic-mirror-filter-rule/${TrafficMirrorFilterRuleId}"},
		{Name: "ec2_traffic_mirror_session", Service: "ec2", Resource: "traffic-mirror-session", Template: "arn:${Partition}:ec2:${Region}:${Account}:traffic-mirror-session/${TrafficMirrorSessionId}"},
		{Name: "ec2_traffic_mirror_target", Service: "ec2", Resource: "traffic-mirror-target", Template: "arn:${Partition}:ec2:${Region}:${Account}:traffic-mirror-target/${TrafficMirrorTargetId}"},
		{Name: "ec2_transit_gateway", Service: "ec2", Resource: "transit-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway/${TransitGatewayId}"},
		{Name: "ec2_transit_gateway_attachment", Service: "ec2", Resource: "transit-gateway-attachment", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-attachment/${TransitGatewayAttachmentId}"},
		{Name: "ec2_transit_gateway_connect_peer", Service: "ec2", Resource: "transit-gateway-connect-peer", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-connect-peer/${TransitGatewayConnectPeerId}"},
		{Name: "ec2_transit_gateway_metering_policy", Service: "ec2", Resource: "transit-gateway-metering-policy", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-metering-policy/${TransitGatewayMeteringPolicyId}"},
		{Name: "ec2_transit_gateway_multicast_domain", Service: "ec2", Resource: "transit-gateway-multicast-domain", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-multicast-domain/${TransitGatewayMulticastDomainId}"},
		{Name: "ec2_transit_gateway_policy_table", Service: "ec2", Resource: "transit-gateway-policy-table", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-policy-table/${TransitGatewayPolicyTableId}"},
		{Name: "ec2_transit_gateway_route_table", Service: "ec2", Resource: "transit-gateway-route-table", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-route-table/${TransitGatewayRouteTableId}"},
		{Name: "ec2_transit_gateway_route_table_announcement", Service: "ec2", Resource: "transit-gateway-route-table-announcement", Template: "arn:${Partition}:ec2:${Region}:${Account}:transit-gateway-route-table-announcement/${TransitGatewayRouteTableAnnouncementId}"},
		{Name: "ec2_verified_access_endpoint", Service: "ec2", Resource: "verified-access-endpoint", Template: "arn:${Partition}:ec2:${Region}:${Account}:verified-access-endpoint/${VerifiedAccessEndpointId}"},
		{Name: "ec2_verified_access_endpoint_target", Service: "ec2", Resource: "verified-access-endpoint-target", Template: "arn:${Partition}:ec2:${Region}:${Account}:verified-access-endpoint-target/${VerifiedAccessEndpointTargetId}"},
		{Name: "ec2_verified_access_group", Service: "ec2", Resource: "verified-access-group", Template: "arn:${Partition}:ec2:${Region}:${Account}:verified-access-group/${VerifiedAccessGroupId}"},
		{Name: "ec2_verified_access_instance", Service: "ec2", Resource: "verified-access-instance", Template: "arn:${Partition}:ec2:${Region}:${Account}:verified-access-instance/${VerifiedAccessInstanceId}"},
		{Name: "ec2_verified_access_policy", Service: "ec2", Resource: "verified-access-policy", Template: "arn:${Partition}:ec2:${Region}:${Account}:verified-access-policy/${VerifiedAccessPolicyId}"},
		{Name: "ec2_verified_access_trust_provider", Service: "ec2", Resource: "verified-access-trust-provider", Template: "arn:${Partition}:ec2:${Region}:${Account}:verified-access-trust-provider/${VerifiedAccessTrustProviderId}"},
		{Name: "ec2_volume", Service: "ec2", Resource: "volume", Template: "arn:${Partition}:ec2:${Region}:${Account}:volume/${VolumeId}"},
		{Name: "ec2_vpc", Service: "ec2", Resource: "vpc", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc/${VpcId}"},
		{Name: "ec2_vpc_block_public_access_exclusion", Service: "ec2", Resource: "vpc-block-public-access-exclusion", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-block-public-access-exclusion/${VpcBlockPublicAccessExclusionId}"},
		{Name: "ec2_vpc_encryption_control", Service: "ec2", Resource: "vpc-encryption-control", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-encryption-control/${VpcEncryptionControlId}"},
		{Name: "ec2_vpc_endpoint", Service: "ec2", Resource: "vpc-endpoint", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-endpoint/${VpcEndpointId}"},
		{Name: "ec2_vpc_endpoint_connection", Service: "ec2", Resource: "vpc-endpoint-connection", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-endpoint-connection/${VpcEndpointConnectionId}"},
		{Name: "ec2_vpc_endpoint_service", Service: "ec2", Resource: "vpc-endpoint-service", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-endpoint-service/${VpcEndpointServiceId}"},
		{Name: "ec2_vpc_endpoint_service_permission", Service: "ec2", Resource: "vpc-endpoint-service-permission", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-endpoint-service-permission/${VpcEndpointServicePermissionId}"},
		{Name: "ec2_vpc_flow_log", Service: "ec2", Resource: "vpc-flow-log", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-flow-log/${VpcFlowLogId}"},
		{Name: "ec2_vpc_peering_connection", Service: "ec2", Resource: "vpc-peering-connection", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpc-peering-connection/${VpcPeeringConnectionId}"},
		{Name: "ec2_vpn_concentrator", Service: "ec2", Resource: "vpn-concentrator", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpn-concentrator/${VpnConcentratorId}"},
		{Name: "ec2_vpn_connection", Service: "ec2", Resource: "vpn-connection", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpn-connection/${VpnConnectionId}"},
		{Name: "ec2_vpn_connection_device_type", Service: "ec2", Resource: "vpn-connection-device-type", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpn-connection-device-type/${VpnConnectionDeviceTypeId}"},
		{Name: "ec2_vpn_gateway", Service: "ec2", Resource: "vpn-gateway", Template: "arn:${Partition}:ec2:${Region}:${Account}:vpn-gateway/${VpnGatewayId}"},
	})
}
